<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Survey Proposal & Quotation — {{ $project->name }}</title>
    <style>
        @page { margin: 15mm 15mm 20mm 15mm; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9.5pt; color: #1e293b; line-height: 1.5; }
        
        .header { border-bottom: 2px solid #0f172a; padding-bottom: 10px; margin-bottom: 15px; }
        .header table { width: 100%; }
        .company-name { font-size: 16pt; font-weight: bold; color: #0f172a; }
        .company-desc { font-size: 7pt; color: #64748b; }
        .doc-title { text-align: right; font-size: 14pt; font-weight: bold; color: #0f172a; }
        .doc-meta { text-align: right; font-size: 8pt; color: #64748b; }

        .info-box { background: #f8fafc; border: 1px solid #e2e8f0; border-left: 3px solid #0f172a; padding: 10px; margin-bottom: 15px; }
        .info-box table { width: 100%; }
        .info-label { font-size: 7.5pt; color: #64748b; text-transform: uppercase; font-weight: bold; }
        .info-value { font-size: 10pt; font-weight: bold; color: #0f172a; }

        .section-title { font-size: 9.5pt; font-weight: bold; text-transform: uppercase; color: #0f172a; border-bottom: 1px solid #cbd5e1; margin-bottom: 8px; margin-top: 15px; }
        
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
        .data-table td { padding: 4px 8px; border: 1px solid #e2e8f0; font-size: 8.5pt; }
        .data-table .label { background: #f8fafc; font-weight: bold; color: #475569; width: 25%; font-size: 7.5pt; }

        .cost-table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        .cost-table thead th { background: #0f172a; color: #fff; padding: 6px 8px; font-size: 7.5pt; text-align: left; }
        .cost-table tbody td { padding: 5px 8px; border-bottom: 1px solid #e2e8f0; font-size: 8.5pt; }
        .cost-table .cat-row td { background: #f1f5f9; font-weight: bold; font-size: 8pt; color: #475569; }
        .cost-table .sub-row td { background: #f8fafc; font-weight: bold; border-top: 1px solid #cbd5e1; }
        .cost-table .grand-row td { background: #0f172a; color: #fff; font-weight: bold; font-size: 10pt; padding: 8px; }
        .text-right { text-align: right; }

        .terms { font-size: 7.5pt; color: #475569; background: #f8fafc; padding: 10px; border: 1px solid #e2e8f0; }
        .terms h4 { margin-top: 0; margin-bottom: 5px; font-size: 8.5pt; color: #0f172a; }
        .terms ol { margin: 0; padding-left: 15px; }
        
        .signature { margin-top: 25px; width: 100%; }
        .signature td { width: 50%; padding-top: 30px; border-top: 1px solid #1e293b; text-align: center; font-size: 8pt; color: #475569; }
        
        .page-break { page-break-before: always; }
    </style>
</head>
<body>

    {{-- HEADER --}}
    <div class="header">
        <table>
            <tr>
                <td style="width: 50%; vertical-align: top;">
                    <div class="company-name">SURVEY ESTIMATION SYSTEM</div>
                    <div class="company-desc">Hydrographic Survey Planning & Quotation<br>Generated by SES v1.0</div>
                </td>
                <td style="width: 50%; vertical-align: top;">
                    <div class="doc-title">SURVEY PROPOSAL & QUOTATION</div>
                    <div class="doc-meta">
                        Ref No: {{ $quotation_number }}<br>
                        Date: {{ $generated_at->format('d F Y') }}
                    </div>
                </td>
            </tr>
        </table>
    </div>

    {{-- CLIENT & PROJECT INFO --}}
    <div class="info-box">
        <table>
            <tr>
                <td style="width: 50%;">
                    <div class="info-label">Quotation To</div>
                    <div class="info-value">{{ $project->client ?? 'Client Name' }}</div>
                </td>
                <td style="width: 50%;">
                    <div class="info-label">Project Details</div>
                    <div class="info-value">{{ $project->name }} ({{ $project->project_code }})</div>
                    <div style="font-size: 7.5pt; color: #64748b;">Location: {{ $project->location ?? 'N/A' }}</div>
                </td>
            </tr>
        </table>
    </div>

    {{-- SCOPE & ENGINEERING SUMMARY --}}
    <div class="section-title">1. Technical Scope of Work</div>
    <table class="data-table">
        <tr>
            <td class="label">Survey Type</td>
            <td>Single Beam Echo Sounder (SBES)</td>
            <td class="label">Total Survey Area</td>
            <td>{{ number_format($total_area_m2, 2) }} m² ({{ number_format($total_area_km2, 4) }} km²)</td>
        </tr>
        <tr>
            <td class="label">Total Survey Lines</td>
            <td>{{ $total_lines }} lines ({{ $main_line_count }} main, {{ $cross_line_count }} cross)</td>
            <td class="label">Total Distance</td>
            <td>{{ number_format($total_length_nm, 4) }} Nautical Miles (NM)</td>
        </tr>
        <tr>
            <td class="label">Line Spacing</td>
            <td>{{ $line_spacing }} m</td>
            <td class="label">Orientation Angle</td>
            <td>{{ $orientation_angle }}°</td>
        </tr>
    </table>

    <div class="section-title">2. Time Estimation</div>
    <table class="data-table">
        <tr>
            <td class="label">Survey Speed</td>
            <td>{{ $duration['speed_knots'] }} knots</td>
            <td class="label">Working Hours/Day</td>
            <td>{{ $duration['hours_per_day'] }} hours</td>
        </tr>
        <tr>
            <td class="label">Survey Execution</td>
            <td>{{ number_format($duration['execution_days'], 2) }} days</td>
            <td class="label">Weather Standby</td>
            <td>{{ $duration['weather_days'] }} days</td>
        </tr>
        <tr>
            <td class="label">MOB/DEMOB</td>
            <td>{{ $duration['mod_demod_days'] }} days</td>
            <td class="label" style="background:#0f172a; color:#fff;">EST. DURATION</td>
            <td style="font-weight:bold; font-size:10pt;">{{ number_format($duration['total_days'], 1) }} DAYS</td>
        </tr>
    </table>

    {{-- COST BREAKDOWN --}}
    <div class="section-title">3. Itemized Cost Quotation</div>
    <table class="cost-table">
        <thead>
            <tr>
                <th style="width: 5%">No.</th>
                <th style="width: 45%">Description</th>
                <th style="width: 12%" class="text-right">Qty</th>
                <th style="width: 18%" class="text-right">Unit Rate (RM)</th>
                <th style="width: 20%" class="text-right">Total (RM)</th>
            </tr>
        </thead>
        <tbody>
            @php $itemNo = 1; $grandTotal = 0; @endphp
            @foreach($grouped_costs as $category => $items)
                <tr class="cat-row"><td colspan="5">{{ $category }}</td></tr>
                @php $catTotal = 0; @endphp
                @foreach($items as $item)
                    <tr>
                        <td>{{ $itemNo++ }}</td>
                        <td>{{ $item->description }}</td>
                        <td class="text-right">{{ number_format($item->quantity, 2) }}</td>
                        <td class="text-right">{{ number_format($item->unit_rate, 2) }}</td>
                        <td class="text-right font-weight-bold">{{ number_format($item->total_price, 2) }}</td>
                    </tr>
                    @php $catTotal += $item->total_price; @endphp
                @endforeach
                <tr class="sub-row">
                    <td colspan="4" class="text-right">{{ $category }} Subtotal</td>
                    <td class="text-right">RM {{ number_format($catTotal, 2) }}</td>
                </tr>
                @php $grandTotal += $catTotal; @endphp
            @endforeach
            <tr class="grand-row">
                <td colspan="4" class="text-right">GRAND TOTAL (MYR)</td>
                <td class="text-right">RM {{ number_format($grandTotal, 2) }}</td>
            </tr>
        </tbody>
    </table>

    {{-- TERMS & SIG --}}
    <div class="terms">
        <h4>Terms & Conditions</h4>
        <ol>
            <li>This quotation is valid for 30 days from the date of issue.</li>
            <li>All prices are quoted in Malaysian Ringgit (MYR).</li>
            <li>The estimated duration is subject to actual weather and sea conditions at the survey site.</li>
            <li>Payment terms: 30% upon confirmation, 70% upon completion of deliverables.</li>
            <li>Any additional survey scope changes will be quoted separately.</li>
        </ol>
    </div>

    <table class="signature">
        <tr>
            <td style="padding-right:20px;">
                Prepared By<br><strong>{{ $project->user->name ?? 'System Administrator' }}</strong><br>Date: {{ $generated_at->format('d/m/Y') }}
            </td>
            <td style="padding-left:20px;">
                Accepted By<br><strong>{{ $project->client ?? 'Client' }}</strong><br>Date: _______________
            </td>
        </tr>
    </table>
</body>
</html>
